/**
 * Test for designation type rows and type conversion.
 *
 * @type row1
 */
select cast(1 as int)             as c_int
,      cast(1.1 as numeric)       as c_numeric
,      cast(2.2 as float)         as c_float
,      cast(3.3 as real)          as c_real
,      cast(4.4 as double)        as c_double
,      cast('varchar' as varchar) as c_varchar
,      cast('text' as text)       as c_text
,      cast('blob' as blob)       as c_blob
